/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISubmitterPayoutInformation,
  ISubmitterPayoutInformationInterface,
} from "../ISubmitterPayoutInformation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "submitter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISubmitterPayoutInformation__factory {
  static readonly abi = _abi;
  static createInterface(): ISubmitterPayoutInformationInterface {
    return new utils.Interface(_abi) as ISubmitterPayoutInformationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISubmitterPayoutInformation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISubmitterPayoutInformation;
  }
}
