/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface InitializedProxyInterface extends ethers.utils.Interface {
  functions: {
    "_paycallback()": FunctionFragment;
    "logic()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_paycallback",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "logic", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "_paycallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logic", data: BytesLike): Result;

  events: {};
}

export class InitializedProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: InitializedProxyInterface;

  functions: {
    _paycallback(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "_paycallback()"(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    logic(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "logic()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  _paycallback(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "_paycallback()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  logic(overrides?: CallOverrides): Promise<string>;

  "logic()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _paycallback(overrides?: CallOverrides): Promise<void>;

    "_paycallback()"(overrides?: CallOverrides): Promise<void>;

    logic(overrides?: CallOverrides): Promise<string>;

    "logic()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    _paycallback(overrides?: PayableOverrides): Promise<BigNumber>;

    "_paycallback()"(overrides?: PayableOverrides): Promise<BigNumber>;

    logic(overrides?: CallOverrides): Promise<BigNumber>;

    "logic()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _paycallback(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "_paycallback()"(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    logic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "logic()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
