/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ISubmitterPayoutInformation } from "./ISubmitterPayoutInformation";

export class ISubmitterPayoutInformationFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISubmitterPayoutInformation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISubmitterPayoutInformation;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getArtistAuctionRoyaltyAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getSubmitterPayoutInformation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
