/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RoyaltyConfig } from "./RoyaltyConfig";

export class RoyaltyConfigFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RoyaltyConfig> {
    return super.deploy(overrides || {}) as Promise<RoyaltyConfig>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RoyaltyConfig {
    return super.attach(address) as RoyaltyConfig;
  }
  connect(signer: Signer): RoyaltyConfigFactory {
    return super.connect(signer) as RoyaltyConfigFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RoyaltyConfig {
    return new Contract(address, _abi, signerOrProvider) as RoyaltyConfig;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "bps",
        type: "uint256",
      },
    ],
    name: "UpdatedRoyalty",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "royalities",
    outputs: [
      {
        internalType: "uint256",
        name: "bps",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "salePrice",
        type: "uint256",
      },
    ],
    name: "royaltyInfo",
    outputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "royaltyAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610253806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806301ffc9a7146100465780632a55205a1461006e578063b5004f01146100a0575b600080fd5b610059610054366004610184565b6100ed565b60405190151581526020015b60405180910390f35b61008161007c3660046101ce565b610124565b604080516001600160a01b039093168352602083019190915201610065565b6100d06100ae3660046101b5565b600060208190529081526040902080546001909101546001600160a01b031682565b604080519283526001600160a01b03909116602083015201610065565b60006001600160e01b0319821663152a902d60e11b148061011e57506301ffc9a760e01b6001600160e01b03198316145b92915050565b600082815260208181526040808320815180830190925280548252600101546001600160a01b03169181018290528291610162620f424060646101f0565b825161016e90876101f0565b61017891906101f0565b92509250509250929050565b60006020828403121561019657600080fd5b81356001600160e01b0319811681146101ae57600080fd5b9392505050565b6000602082840312156101c757600080fd5b5035919050565b600080604083850312156101e157600080fd5b50508035926020909101359150565b600081600019048311821515161561021857634e487b7160e01b600052601160045260246000fd5b50029056fea2646970667358221220ebea143b196442dcef0b927d90ead7f66940b08a97222e752235e56ab069849664736f6c63430008050033";
